"""Simulator and Scorer for the VBPCApy trade study.

These implement the ``trade_study.Simulator`` and ``trade_study.Scorer``
protocols and are used by every phase script.
"""

from __future__ import annotations

import time
from typing import Any

import numpy as np

from vbpca_py import (
    VBPCA,
    CVConfig,
    SelectionConfig,
    cross_validate_components,
    select_n_components,
)

from ._common import (
    ACTIVE_CRITERIA_PRESETS,
    CRITERION_ORDER_LEVELS,
    FIXED_STRUCTURAL,
    HOLDOUT_FRACTION,
    QUALITY_COMPOSITE_WEIGHTS,
    RNG_SEED,
    apply_missingness,
    generate_low_rank,
    holdout_split,
)


class VBPCASimulator:
    """Generate synthetic data and fit VBPCA.

    Each ``config`` dict contains both *tunable factor* values
    (``hp_va``, ``maxiters``, …) and *data-regime* values
    (``n``, ``p``, ``true_rank``, ``missingness``, ``noise_std``).

    When ``regime_defaults`` is provided (e.g. during adaptive
    refinement), missing regime keys are filled from the defaults
    so that configs generated by optuna — which only contain
    tunable-factor values — still produce valid trials.

    The generate method:

    1. Creates a low-rank-plus-noise matrix for the regime.
    2. Applies missingness and holdout split.
    3. Fits VBPCA with the tunable factor values.
    4. Runs model selection using the configured metric mode.
    5. Returns ``(truth_dict, observations_dict)``.
    """

    def __init__(self, *, regime_defaults: dict[str, Any] | None = None) -> None:
        self._regime_defaults: dict[str, Any] = regime_defaults or {}

    def generate(self, config: dict[str, Any]) -> tuple[Any, Any]:
        """Run a single trial and return (truth, observations)."""
        config = {**FIXED_STRUCTURAL, **self._regime_defaults, **config}
        rng = np.random.default_rng(config.get("seed", RNG_SEED))

        # ── Data regime ─────────────────────────────────────────
        n: int = config["n"]
        p: int = config["p"]
        true_rank: int = config["true_rank"]
        noise_std: float = config["noise_std"]
        missingness: str = config["missingness"]

        x_true = generate_low_rank(n, p, true_rank, noise_std, rng)
        obs_mask = apply_missingness(x_true, missingness, rng)
        train_mask, holdout_mask = holdout_split(obs_mask, HOLDOUT_FRACTION, rng)

        # ── Map tunable factors → VBPCA kwargs ─────────────────
        vbpca_kw: dict[str, Any] = {"verbose": 0}
        for key in (
            "hp_va",
            "hp_vb",
            "hp_v",
            "va_init",
            "niter_broadprior",
            "maxiters",
            "minangle",
            "patience",
            "cfstop_rel",
            "rotate2pca",
            "bias",
            "xprobe_fraction",
        ):
            if key in config and config[key] is not None:
                vbpca_kw[key] = config[key]

        # Compound rmsstop array
        if "rmsstop_window" in config:
            vbpca_kw["rmsstop"] = [
                config["rmsstop_window"],
                config.get("rmsstop_atol", 1e-4),
                config.get("rmsstop_rtol", 1e-3),
            ]

        # Criterion ordering (v2) — resolve preset name to list.
        if "criterion_order" in config and config["criterion_order"] is not None:
            co = config["criterion_order"]
            vbpca_kw["criterion_order"] = (
                CRITERION_ORDER_LEVELS[co]
                if isinstance(co, str) and co in CRITERION_ORDER_LEVELS
                else co
            )

        # Active criteria (v2) — resolve preset name to dict.
        if "active_criteria" in config and config["active_criteria"] is not None:
            ac = config["active_criteria"]
            vbpca_kw["convergence_criteria"] = (
                ACTIVE_CRITERIA_PRESETS[ac]
                if isinstance(ac, str) and ac in ACTIVE_CRITERIA_PRESETS
                else ac
            )

        # ── Model selection ─────────────────────────────────────
        max_k = min(true_rank + 5, min(p, n) - 1)
        max_k = max(max_k, true_rank + 2)

        selection_mode = str(config.get("selection_mode", "cost"))

        # Pull maxiters out of vbpca_kw so it's passed as a kwarg
        # to select_n_components (which forwards to VBPCA).
        maxiters = vbpca_kw.pop("maxiters", 200)

        t0 = time.perf_counter()
        if selection_mode in {"cv_prms", "cv_cost"}:
            cv_metric = "prms" if selection_mode == "cv_prms" else "cost"
            cv_k, cv_results = cross_validate_components(
                x_true,
                mask=train_mask,
                components=range(1, max_k + 1),
                config=CVConfig(
                    metric=cv_metric, n_splits=5, seed=int(config.get("seed", RNG_SEED))
                ),
                maxiters=maxiters,
                **vbpca_kw,
            )
            best_k = int(cv_k)
            best_model = VBPCA(best_k, maxiters=maxiters, verbose=0, **vbpca_kw)
            best_model.fit(x_true, mask=train_mask)
            trace = [
                {
                    "k": int(row["k"]),
                    "rms": float(row.get("mean_rms", float("nan"))),
                    "prms": float(row.get("mean_prms", float("nan"))),
                    "cost": float(row.get("mean_cost", float("nan"))),
                    "n_iter": 0,
                    "convergence_reason": f"cv_{cv_metric}",
                }
                for row in cv_results
            ]
        else:
            sel_metric = "cost"
            if selection_mode in {"prms", "rms", "cost"}:
                sel_metric = selection_mode
            sel_cfg = SelectionConfig(
                metric=sel_metric,
                patience=2,
                max_trials=max_k,
                return_best_model=True,
            )
            best_k, _best_metrics, trace, best_model = select_n_components(
                x_true,
                mask=train_mask,
                config=sel_cfg,
                maxiters=maxiters,
                **vbpca_kw,
            )
        wall_seconds = time.perf_counter() - t0

        # Fallback: if select_n_components didn't return a model,
        # refit at the chosen k.
        if best_model is None:
            best_model = VBPCA(best_k, maxiters=maxiters, verbose=0, **vbpca_kw)
            best_model.fit(x_true, mask=train_mask)
            wall_seconds = time.perf_counter() - t0

        # ── Convergence diagnostics ─────────────────────────────
        total_iters = sum(int(t.get("n_iter", 0)) for t in trace)
        best_k_iters = int(best_model.n_iter_ or 0)

        truth = {
            "x_true": x_true,
            "holdout_mask": holdout_mask,
            "true_rank": true_rank,
        }
        observations = {
            "x_rec": best_model.reconstruction_,
            # Predictive variance (latent uncertainty + observation noise)
            # gives calibrated intervals; fall back to latent-only variance
            # if the predictive term is unavailable.
            "x_var": (
                best_model.predictive_variance_
                if best_model.predictive_variance_ is not None
                else best_model.variance_
            ),
            "selected_k": best_k,
            "model": best_model,
            "trace": trace,
            "wall_seconds": wall_seconds,
            "total_iters": total_iters,
            "best_k_iters": best_k_iters,
        }
        return truth, observations


class VBPCAScorer:
    """Score a VBPCA fit against ground truth.

    Returns a dict of floats matching the observable names in
    ``_common.observables``.
    """

    def score(
        self,
        truth: Any,
        observations: Any,
        config: dict[str, Any],
    ) -> dict[str, float]:
        """Compute all response metrics for one trial."""
        x_true: np.ndarray = truth["x_true"]
        holdout: np.ndarray = truth["holdout_mask"]
        true_rank: int = truth["true_rank"]

        x_rec = observations["x_rec"]
        x_var = observations["x_var"]
        selected_k: int = observations["selected_k"]
        wall_seconds: float = observations["wall_seconds"]

        # ── Reconstruction quality ─────────────────────────────
        residuals = (x_true - x_rec)[holdout]
        holdout_rmse = float(np.sqrt(np.mean(residuals**2)))
        holdout_mae = float(np.mean(np.abs(residuals)))

        # ── Posterior interval metrics ─────────────────────────
        if x_var is not None and np.isfinite(x_var).all():
            z = 1.96  # 95 % two-sided normal quantile
            std = np.sqrt(np.maximum(x_var, 0.0))
            lower = x_rec - z * std
            upper = x_rec + z * std

            in_interval = (x_true >= lower) & (x_true <= upper)
            coverage_95 = float(in_interval[holdout].mean())

            widths = (upper - lower)[holdout]
            mean_width = float(widths.mean())

            # Interval score (proper scoring rule)
            alpha = 0.05
            below = x_true[holdout] < lower[holdout]
            above = x_true[holdout] > upper[holdout]
            penalty_below = (2.0 / alpha) * (lower[holdout] - x_true[holdout]) * below
            penalty_above = (2.0 / alpha) * (x_true[holdout] - upper[holdout]) * above
            interval_score = float(np.mean(widths + penalty_below + penalty_above))
        else:
            coverage_95 = 0.0
            mean_width = float("inf")
            interval_score = float("inf")

        calibration_gap = abs(0.95 - coverage_95)
        rank_mae = float(abs(selected_k - true_rank))
        rank_under = float(max(0, true_rank - selected_k))
        rank_over = float(max(0, selected_k - true_rank))
        rank_penalty = float(rank_under * rank_under + 0.25 * rank_over)

        total_iters: int = observations.get("total_iters", 0)
        best_k_iters: int = observations.get("best_k_iters", 0)

        return {
            "holdout_rmse": holdout_rmse,
            "holdout_mae": holdout_mae,
            "coverage_95": coverage_95,
            "rank_mae": rank_mae,
            "rank_under": rank_under,
            "rank_over": rank_over,
            "rank_penalty": rank_penalty,
            "interval_score": interval_score,
            "calibration_gap": calibration_gap,
            "wall_seconds": wall_seconds,
            "total_iters": float(total_iters),
            "best_k_iters": float(best_k_iters),
        }


def compute_quality_composite(
    scores: dict[str, float],
    bounds: dict[str, tuple[float, float]],
    weights: dict[str, float] | None = None,
) -> float:
    """Compute a weighted min-max normalised quality composite.

    Parameters
    ----------
    scores
        Per-observable raw scores for a single trial (must include
        ``holdout_rmse``, ``coverage_95``, ``rank_mae``).
    bounds
        ``{name: (lo, hi)}`` min-max bounds for normalisation, computed
        over the current phase sample.  For coverage_95 the bounds apply
        to ``1 - coverage_95`` (so that MINIMIZE direction is consistent).
    weights
        Per-metric weights.  Defaults to
        :data:`~._common.QUALITY_COMPOSITE_WEIGHTS`.

    Returns
    -------
    float
        Composite value in [0, 1] (lower is better).
    """
    if weights is None:
        weights = QUALITY_COMPOSITE_WEIGHTS

    total = 0.0
    for name, w in weights.items():
        raw = scores[name]
        # Flip coverage so MINIMIZE is better (like RMSE/rank_mae).
        if name == "coverage_95":
            raw = 1.0 - raw
        lo, hi = bounds[name]
        span = hi - lo
        normed = (raw - lo) / span if span > 0 else 0.0
        total += w * max(0.0, min(1.0, normed))
    return total
